services:
  db:
    image: postgres:17
    container_name: postgres17practice
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviesdbpractice
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4Practice
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: umair@nanu.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8084:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local